### ISSUE TITLE
GH Actions bug

### ISSUE THREAD

**Issue by arvkevi** [arvkevi/kneed#148]
There's a bug in the workflow file. 

Pull request events are checking out the ref from main. See the checkout step of [this job](https://github.com/arvkevi/kneed/actions/runs/4829749517/jobs/8605149399) in #147 is checking out c525bbbe8cd6a78a66be1535c031c05d8ad9a321.

The desired workflow is to checkout the most recent commit on the pr branch and run tests on it.

**Comment by Shotgunosine** [comment]
So I think this is because the action is creating a temporary merge commit and checking that out:
https://github.com/actions/checkout/issues/426. Commit 525bbb isn't in the main repo's git log, or in the PR's git log. It's a new commit simulating the results of merging the PR.

Line 48 here hints at this:
https://github.com/arvkevi/kneed/actions/runs/4829749517/jobs/8605149399#step:2:53
"/usr/local/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +c525bbbe8cd6a78a66be1535c031c05d8ad9a321:refs/remotes/pull/147/**merge**"
