### ISSUE TITLE
Unable to detect knee and elbow

### ISSUE THREAD

**Issue by dpapadop** [arvkevi/kneed#88]
```
import numpy as np
import pandas as pd
from kneed import KneeLocator 

import matplotlib.pyplot as plt
```

Having the following dummy data:

```
np.random.seed(42)
y1 = np.random.randint(5,10,5)
y2 = np.random.randint(15,20,5)
y3 = np.random.randint(5,10,5)

y = np.append(y1 , y2)
y = np.append(y , y3)
y_cum = y.cumsum()

df_test = pd.DataFrame({'x': range(len(y)), 'y_cum': y_cum, 'y': y})
```
If we plot these data we can see an "elbow" (at 4 in the x-axis) and a "knee" (at 9 in the x-axis)
`plt.plot(df_test['x'], df_test['y_cum'])`
![image](https://user-images.githubusercontent.com/37326660/102510618-7e197d00-4090-11eb-8466-ef777766ba52.png)

But if I run 
```
kneedle = KneeLocator(df_test['x'], df_test['y'], curve='convex', direction='increasing', online=False, S=1)
elbow_point = kneedle.elbow
elbow_point
```
I get 13 as elbow point

and  if i run

```
kneedle = KneeLocator(df_test['x'], df_test['y'], curve='concave', direction='increasing', online=False, S=1)
elbow_point = kneedle.elbow
elbow_point
```
I get 1 as elbow point

And if I run 

```
kneedle = KneeLocator(df_test['x'], df_test['y'], curve='convex', direction='increasing', online=True, S=1)
elbow_point = kneedle.elbow
elbow_point
```

and 

```
kneedle = KneeLocator(df_test['x'], df_test['y'], curve='concave', direction='increasing', online=True, S=1)
elbow_point = kneedle.elbow
elbow_point
```
so the same as before but with `online=True`

I get 13 & 1 as elbow points respectively

For completeness these are the randomly generated data: 
```
x : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
y_cum : [8, 17, 24, 33, 42, 58, 75, 92, 109, 128, 136, 143, 152, 158, 166]
```

**Comment by d-kleine** [comment]
@dpapadop I have just looked into your bug report. As far as I understand, you want to locate both knee and elbow for the given plot. Why do you use `df_test['y']` when plotting `y_cum`? y and `y_cum` are complete different:
`plt.plot(df_test['x'], df_test['y'])`
![lineplot](https://user-images.githubusercontent.com/53251018/116737220-408b1000-a9f1-11eb-9be7-d3a3491afb5f.png)

But I could reproduce your issue. I have transposed x and y and then somehow the elbow has been found at x=42 (and y=4), but for the knee I got x=136 (y=10 instead of y=9)

```
kneedle = KneeLocator(x=df_test['y_cum'], y=df_test['x'], curve='concave', direction='increasing', online=False, S=1)
elbow_point = kneedle.elbow
elbow_point
```

```
kneedle = KneeLocator(x=df_test['y_cum'], y=list(range(len(y))), curve='convex', direction='increasing', online=False, S=1)
knee_point = kneedle.knee
knee_point
```
![knee-elbow](https://user-images.githubusercontent.com/53251018/116738158-61a03080-a9f2-11eb-9240-adee96091355.png)

Kind regards
DK
